name: 'Jira Transition'
description: 'Transition Jira issues'
author: itdesign GmbH
inputs:
  transition_name:
    description: 'Name of the Transition'
    required: true
  service_base_url:
    description: 'Base URL of the transition service, including credentials'
    required: true
  search_pattern:
    description: 'Search pattern to search for Jira issues in git logs'
    required: false
  ignore_pattern:
    description: 'Ignore pattern that excludes issues references in this line of the commit message'
    required: false
  commit_depth:
    description: 'Git Commit Depth'
    required: false
  additional_jql:
    description: 'Additional jql that should be included'
    required: false
runs:
  using: 'node20'
  main: 'dist/index.js'
branding:
  icon: 'arrow-right-circle'
  color: 'blue'
